# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      time: "06:00"
      interval: "daily"
    assignees:
      - "hexa2k9"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      time: "06:00"
      interval: "daily"
    assignees:
      - "hexa2k9"
