variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  REGISTRY_ORG: "port389"
  QUAY_REGISTRY: "quay.io"

build image:
  image: docker:stable
  stage: build
  tags:
    - dockersock
  variables:
    DOCKER_IMAGE: ${QUAY_REGISTRY}/${REGISTRY_ORG}/sonar-scanner
  before_script:
    - docker login -u "${QUAY_USER}" -p "${QUAY_PASSWORD}" ${QUAY_REGISTRY}
  script:
    - docker build --pull --tag "${DOCKER_IMAGE}"  "4"
    - docker push ${DOCKER_IMAGE}
