variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  REGISTRY_ORG: "port389"
  QUAY_REGISTRY: "quay.io"

build image:
  image: docker:stable
  stage: build
  tags:
    - dockersock
  variables:
    DOCKER_IMAGE: ${QUAY_REGISTRY}/${REGISTRY_ORG}/sonar-scanner:${SONAR_SCANNER_VERSION}
  before_script:
    - docker login -u "${QUAY_USER}" -p "${QUAY_PASSWORD}" ${QUAY_REGISTRY}
  script:
    - docker build --build-arg SONAR_SCANNER_VERSION=${SONAR_SCANNER_VERSION} --pull --tag "${DOCKER_IMAGE}"  "4"
    - docker push ${DOCKER_IMAGE}
  parallel:
    matrix:
      - SONAR_SCANNER_VERSION:
          - 4.5.0.2216
          - 4.6.0.2311
          - 4.6.1.2450
          - 4.6.2.2472
